// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package coldstartprocessor correlates cold start information generated by the telemetryapireceiver
// with incoming span data.
//
// It reads the following of incoming Lambda execution spans identified by the faas.execution attribute:
//
//   - trace ID
//   - parent span ID
//   - span scope
//   - resource attributes
//
// This information is stored until the first coldstart span identified by the faas.coldstart attribute
// is received. That span's trace ID, parent span ID are updated to match the execution span. This
// allows the coldstart span to be part of the same trace as the operation that triggered the cold start. Additionally,
// the span scope and resource attributes of the span scope containing the coldstart span
// are replaced with the span scope and resource attributes of the execution span as
// they contain more details.
package coldstartprocessor // import "github.com/open-telemetry/opentelemetry-lambda/collector/processor/coldstartprocessor"
