# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/collector"
      - "/collector/internal/tools"
      - "/collector/lambdacomponents"
      - "/collector/lambdalifecycle"
      - "/collector/processor/coldstartprocessor"
      - "/collector/processor/decoupleprocessor"
      - "/collector/receiver/telemetryapireceiver"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-deps-collector:
        patterns:
          - "*opentelemetry*"
      collector-other:
        patterns:
          - "*"
