include-fragments = true

accept = ["200..=299", "429"]

exclude  = [
    "^http(s)?://localhost",
    "^http(s)?://example.com",
    "https://docs.aws.amazon.com",
    "https://console.aws.amazon.com"
]

# better to be safe and avoid failures
max-retries = 6
