# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:

    - title: Collector
      labels:
        - go

    - title: Python
      labels:
        - python

    - title: Javascript
      labels:
        - javascript

    - title: Java
      labels:
        - java

    - title: Other Dependencies
      labels:
        - dependencies

    - title: Other
      labels:
        - '*'
