name: 'Build Node.js Lambda Layer'
description: 'Builds the OpenTelemetry Node.js Lambda layer'

outputs:
  artifact-path:
    description: 'Absolute path to the built layer zip'
    value: ${{ github.workspace }}/nodejs/packages/layer/build/opentelemetry-nodejs-layer.zip
  component-version:
    description: 'OpenTelemetry Node.js SDK version included in the layer'
    value: ${{ steps.version.outputs.component-version }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version-file: 'nodejs/.nvmrc'

    - name: Build Node.js layer
      shell: bash
      working-directory: nodejs
      run: |
        npm ci
        npm run build

    - name: Save Node.js SDK version
      id: version
      shell: bash
      working-directory: nodejs/packages/layer/scripts
      run: |
        SDK_VERSION=$(npm list @opentelemetry/core --depth=0 | grep @opentelemetry/core | sed 's/^.*@//')
        echo "component-version=$SDK_VERSION" >> "$GITHUB_OUTPUT"

    - name: Rename layer zip
      shell: bash
      working-directory: nodejs/packages/layer/build
      run: mv layer.zip opentelemetry-nodejs-layer.zip
