AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OpenTelemetry Python Lambda layer for Python
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./function
      Description: Build OTel Python Lambda Sample from scratch
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - Statement:
          - Sid: AMPRemoteWrite
            Effect: Allow
            Action:
            - aps:RemoteWrite
            Resource: '*'
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/otel-instrument
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python  # needed because https://github.com/open-telemetry/opentelemetry-python/issues/2717 / when new release of library is released this should be solved and can be removed 
      Tracing: Active
      Layers:
        - !Ref OTelLayer
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: GET
  OTelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: opentelemetry-python
      Description: Opentelemetry Python layer
      ContentUri: ./otel
      CompatibleRuntimes:
        - python3.9
        - python3.8
    Metadata:
      BuildMethod: makefile
