AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OpenTelemetry Python Lambda layer for Python
Parameters:
  LayerName:
    Type: String
    Description: Lambda layer name to be published
    Default: opentelemetry-python
Resources:
  OTelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Opentelemetry Python layer
      ContentUri: ./otel
      CompatibleRuntimes:
        - python3.8
        - python3.9
        - python3.10
        - python3.11
        - python3.12
        - python3.13
    Metadata:
      BuildMethod: makefile
