#!/bin/bash

set -ef -o pipefail

export JAVA_TOOL_OPTIONS="-javaagent:/opt/opentelemetry-javaagent.jar ${JAVA_TOOL_OPTIONS}"

if [[ $OTEL_RESOURCE_ATTRIBUTES != *"service.name="* ]]; then
  export OTEL_RESOURCE_ATTRIBUTES="service.name=${AWS_LAMBDA_FUNCTION_NAME},${OTEL_RESOURCE_ATTRIBUTES}"
fi

if [[ -z "$OTEL_PROPAGATORS" ]]; then
  export OTEL_PROPAGATORS="tracecontext,baggage,xray"
fi

export OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT=10000

########################################

ARGS=("$@")
EXTRA_ARGS=()

if [ "${OTEL_JAVA_AGENT_FAST_STARTUP_ENABLED}" == "true" ]; then
  echo "[OTEL] Enabling fast startup mode ..."
  # Disable bytecode verification
  EXTRA_ARGS+=("-Xverify:none")
  # Be sure that tiered compilation is enabled
  EXTRA_ARGS+=("-XX:+TieredCompilation")
  # Stop tiered compilation at level 1
  EXTRA_ARGS+=("-XX:TieredStopAtLevel=1")
  for i in "${!ARGS[@]}"; do
    # If tiered compilation is disabled, ignore it as we enable it at level 1 for fast startup
    if [[ ${ARGS[i]} = "-XX:-TieredCompilation" ]]; then
      unset 'ARGS[i]'
    fi
  done
fi

ARGS=("${ARGS[0]}" "${EXTRA_ARGS[@]}" "${ARGS[@]:1}")

exec "${ARGS[@]}"
