AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OpenTelemetry Ruby Lambda layer for Ruby
Parameters:
  LayerName:
    Type: String
    Description: Lambda layer name to be published
    Default: opentelemetry-ruby
Resources:
  OTelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: Opentelemetry Ruby layer
      ContentUri: ./layer
      CompatibleRuntimes:
        - ruby3.2
    Metadata:
      BuildMethod: makefile
