#!/bin/bash


# TODO(anuraaga): Loosen parsing of env variable since it's common to use this sort of pattern in shell scripts.
# https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py#L273
#if [[ $OTEL_RESOURCE_ATTRIBUTES != *"service.name="* ]]; then
#export OTEL_RESOURCE_ATTRIBUTES="service.name=${AWS_LAMBDA_FUNCTION_NAME},${OTEL_RESOURCE_ATTRIBUTES}"
#fi

export OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT=10000

export PYTHONPATH="/opt/python:$LAMBDA_TASK_ROOT:$LAMBDA_RUNTIME_DIR:$PYTHONPATH"

export OTEL_INSTRUMENTATION_AWS_LAMBDA_HANDLER="$_HANDLER"
# Note, the file structure is important. Lambda does not seem to allow loading the handler if it is placed at a
# subdirectory such as opentelemetry.instrumentation.lambda.handler, when inside a layer it must be at the top level.
export _HANDLER="otel_wrapper.lambda_handler"

exec /opt/python/bin/opentelemetry-instrument "$@"
