name: "Continuous Build (NodeJS)"

on:
  push:
    paths:
      - 'nodejs/**'
      - '.github/workflows/ci-nodejs.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'nodejs/**'
      - '.github/workflows/ci-nodejs.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'nodejs/.nvmrc'
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        working-directory: nodejs
      - run: npm run lint
        working-directory: nodejs
      - run: npm test
        working-directory: nodejs
      - name: Build AWS SDK Sample
        run: npm run build
        working-directory: nodejs/sample-apps/aws-sdk
