name: "Continuous Build (Terraform)"

on:
  push:
    paths:
      - '**/*.tf'
      - '.github/workflows/ci-terraform.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/ci-terraform.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - run: terraform fmt -check -recursive
