name: "Continuous Build (Terraform)"

on:
  push:
    paths:
      - '**/*.tf'
      - '.github/workflows/ci-terraform.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/ci-terraform.yml'
    branches:
      - main

permissions:
  contents: read

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - run: terraform fmt -check -recursive
