name: cxdl-api-ingestion
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]


jobs:
    CODE-CI:
      if: startsWith(github.event.ref, 'refs/tags/v') == false
      uses: CXEPI/CPX-CODE-CI/.github/workflows/aux-app-serverless.yml@v2.0.14
      with:
        classification: app-serverless
        build_language: go
      secrets: inherit
