name: Check PR

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    name: Labels
    permissions:
      issues: write # required for creating labels
      pull-requests: write # required for adding labels to pr
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
