name: "Release NodeJS Lambda Layer"

on:
  # (Using tag push instead of release to allow filtering by tag prefix.)
  push:
    tags:
      - layer-nodejs/**

permissions:
  contents: read

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Create Release
        run: gh release create ${{ github.ref_name }} --draft --title ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-layer:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    needs: create-release
    outputs:
      NODEJS_VERSION: ${{ steps.save-node-sdk-version.outputs.SDK_VERSION}}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          npm run build
        working-directory: nodejs

      - name: Save Node SDK Version
        id: save-node-sdk-version
        run: |
          SDK_VERSION=$(npm list @opentelemetry/core --depth=0 | grep @opentelemetry/core | sed 's/^.*@//')
          echo "SDK_VERSION=$SDK_VERSION" >> $GITHUB_OUTPUT
        working-directory: nodejs/packages/layer/scripts

      - name: Rename zip file
        run: mv layer.zip opentelemetry-nodejs-layer.zip
        working-directory: nodejs/packages/layer/build

      - name: Generate artifact attestation for nodejs-layer
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a  #v3.0.0
        with:
          subject-path: nodejs/packages/layer/build/opentelemetry-nodejs-layer.zip
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: Save assembled layer to build
        with:
          name: opentelemetry-nodejs-layer.zip
          path: nodejs/packages/layer/build/opentelemetry-nodejs-layer.zip
          
      - name: Add Binary to Release
        run: |
          gh release upload ${{github.ref_name}} nodejs/packages/layer/build/opentelemetry-nodejs-layer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-layer:
    permissions: # required by the reusable workflow
      contents: read
      id-token: write
    uses: ./.github/workflows/layer-publish.yml
    needs: build-layer
    strategy:
      matrix:
        aws_region:
          - ap-northeast-1
          - ap-northeast-2
          - ap-south-1
          - ap-southeast-1
          - ap-southeast-2
          - ca-central-1
          - eu-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - sa-east-1
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
    with:
      artifact-name: opentelemetry-nodejs-layer.zip
      layer-name: opentelemetry-nodejs
      component-version: ${{needs.build-layer.outputs.NODEJS_VERSION}}
      # architecture:
      # If you add a nodejs runtime here, please make sure that the collector/Makefile publish and publish-layer targets
      # get updated as well
      runtimes: nodejs18.x nodejs20.x nodejs22.x
      release-group: prod
      aws_region: ${{ matrix.aws_region }}
    secrets: inherit
